### ISSUE TITLE
RETH isn't in the list anymore

### ISSUE THREAD

**Issue by vinidlidoo** [alangrainger/cryptorates.ai#14]
=QUERY(IMPORTDATA("https://cryptorates.ai/files/standard.csv", ",", "en_US"), "SELECT Col3 WHERE Col1 = 'RETH'", 0) returns N/A on Google Sheets

**Comment by alangrainger** [comment]
I won't be adding wrapped tokens. 

Think of how many possibilities there are now and in the future for a wrapped token on a different chain. They're going to use up a huge chunk of the top 5000 coins for no benefit - it should be the same token with a nearly identical price.

If a wrapped token is depegging and you wanted to track that price difference, this isn't the tool either since the price will be up to 30 minutes out of date and you could get screwed.

Discussion welcome if someone can provide a useful need for having wrapped tokens along with the base token.

**Comment by alangrainger** [comment]
Let me check into this one as I'm not certain if it's possible to get the RETH price from CMC via API.

**Comment by vinidlidoo** [comment]
I'd be suprised if it didn't. RETH ranks 11th highest market cap on CMC's list of rehypothecated tokens: https://coinmarketcap.com/view/rehypothecated-crypto/

**Comment by alangrainger** [comment]
I like your enthusiasm, but I cannot find any way to get rehypothecated tokens from CMC API:

https://coinmarketcap.com/api/documentation/v1/

**Comment by alangrainger** [comment]
Ahhh, I see the issue.

That rank of 11 is for the category of rehypothecated ETH tokens.

RETH ranks number 9669, so it's outside the top 5000:

```
    id: 15060,
    name: 'Rocket Pool ETH',
    symbol: 'RETH',
    slug: 'rocket-pool-eth',
    circulating_supply: 495598.38857754,
    total_supply: 495598.38857754,
    cmc_rank: 9669,
```

**Comment by alangrainger** [comment]
RETH is now added :+1: 

That ranking above is by market cap, so I am trialling changing the sort order to volume 24 hours.

This is possibly even better because market cap is pretty dodgy, and changing to volume should help currently popular tokens to show up easier.

This also has the benefit that RETH is now included in the dataset, since it's number 1100 by volume.

**Comment by vinidlidoo** [comment]
Confirmed it works on my end. Thank you so much. You're doing god's work.

**Comment by alangrainger** [comment]
All I ask is you spread the word about the service :100:
