### ISSUE TITLE
RETH, STETH, and WETH all missing now

### ISSUE THREAD

**Issue by mrmrdan** [alangrainger/cryptorates.ai#15]
RETH, STETH, and WETH all missing now, both from standard and full csv lists

**Comment by chlarsen** [comment]
As well as mSOL

**Comment by Extended3652** [comment]
MATICX was missing for a while, but it's back now.  Still missing RETH, STETH, and WETH.

**Comment by alangrainger** [comment]
I won't be adding wrapped tokens. 

Think of how many possibilities there are now and in the future for a wrapped token on a different chain. They're going to use up a huge chunk of the top 5000 coins for no benefit - it should be the same token with a nearly identical price.

If a wrapped token is depegging and you wanted to track that price difference, this isn't the tool either since the price will be up to 30 minutes out of date and you could get screwed.

Discussion welcome if someone can provide a useful need for having wrapped tokens along with the base token.

**Comment by alangrainger** [comment]
I have changed the rankings from market cap to volume 24hours, which means that these tokens are now included in the dataset.

**Comment by Extended3652** [comment]
Hi Alan,

There's been an issue with RETH over the last 24 hours where it is stuck
showing .2186 under Change 24h; I'm wondering if you might be able to take
a look at it whenever you get a chance.  Very much appreciated,

Take care,
Matthew

**Comment by alangrainger** [comment]
Hi @Extended3652 - that's because the RETH you're looking at is "[StaFI Staked ETH](https://coinmarketcap.com/currencies/stafi-staked-eth/)", which is higher ranked than Rocket Pool ETH, so it has "stolen" the RETH symbol.

To ensure symbol uniqueness, in the case of conflicts I use this naming convention:

https://cryptorates.ai/naming-convention

You can return Rocket Pool by either using its resulting symbol `RETH_15060`, or by filtering by its full name:

```
=QUERY(IMPORTDATA("https://cryptorates.ai/files/full.csv", ",", "en_US"), "SELECT * WHERE Col2='Rocket Pool ETH'")
```

**Comment by Extended3652** [comment]
That worked; thank you very much for your help!

**Comment by Extended3652** [comment]
Hi Alan,

Sorry to bother you again.  I'm wondering if you've dropped support for
MATICX.  I checked the full csv, but didn't see MATICX or Stader
Maticx listed.  I appreciate your time, and thank you again for the
resource.

Take care,
Matthew

**Comment by alangrainger** [comment]
Hi @Extended3652 - for your reference, I do not drop support for anything. If a coin is in the top 5000 coins by 24h volume, it will show up in the dataset. Every coin that matches that criteria will be in there, I do not filter or drop support for anything.

If MATICX isn't in the top 5000 by volume, it won't appear. However right now it does appear as row 4868:

![image](https://github.com/user-attachments/assets/18271ce4-062a-4604-9344-ecc98f696c3c)

**Comment by Extended3652** [comment]
Thanks for the explanation, that makes sense. It must have dropped out of
the top 5000 when I pulled that last csv.

Take care,
Matthew
