### ISSUE TITLE
CMC Wrapped/Restaked Assets missing

### ISSUE THREAD

**Issue by CryptoSenpaiii** [alangrainger/cryptorates.ai#17]
**Current behavior** 
Since CMC is filtering out Wrapped/Restaked Assets of their Global ranking (see https://coinmarketcap.com/academy/article/cmc-data-becomes-more-accurate#header-2 ) , the dataset is not "complete" anymore. A lot of well known tickers are not included anymore.

**Expected behavior**
The dataset includes top 5000 tickers from ALL crypto assets (doesn't matter if Wrapped/Restaked or not).

**Idea**
Keep the current behavior, if there is a use case for it and introduce a new dataset next to `standard` and `full` to get the "old" behavior again.

**Comment by alangrainger** [comment]
Sadly CMC doesn't seem to provide any API endpoint I can find that returns wrapped token data.

What is the use-case where for example you need WETH but not ETH? They should have the same price unless something has gone seriously wrong with the token, in which case this price database isn't what you're looking for anyway, since it's only updated every 30 mins.

**Comment by alangrainger** [comment]
Having a further think about it, I won't be adding wrapped tokens. 

Think of how many possibilities there are now and in the future for a wrapped token on a different chain. They're going to use up a huge chunk of the top 5000 coins for no benefit - it should be the same token with a nearly identical price.

If a wrapped token is depegging and you wanted to track that price difference, this isn't the tool either since the price will be up to 30 minutes out of date and you could get screwed.

Discussion welcome if someone can provide a useful need for having wrapped tokens along with the base token.

**Comment by alangrainger** [comment]
I have changed the rankings from market cap to volume 24hours, which means that these tokens are now included in the dataset.
