### ISSUE TITLE
Changing order of rows

### ISSUE THREAD

**Issue by Allerius8** [alangrainger/cryptorates.ai#4]
Hello, all works great but I am having this issue. Basically I think the sheet is set up in a way that its sorted by market cap. Meaning if the price of coins changes so might the order. When I have another sheet referencing those cells and it changes ,the price is of course completely different. 

Is there a way to remove the sorting or lock them in place? Or am I doing something wrong?

I dont want to check each time if the cell I am referencing to is really the coin that I want to reference.

**Comment by alangrainger** [comment]
Strongly recommend you use an INDEX / MATCH or a VLOOKUP like it mentions in the docs, rather than referencing a cell by row/column.

Or use the QUERY:

```
=QUERY(IMPORTDATA("https://cryptorates.ai/files/standard.csv", ",", "en_US"), "SELECT Col3 WHERE Col1 = 'BTC'", 0)
```

---

If you want to make it alphabetical, just use a `SORT`:

```
=SORT(IMPORTDATA("https://cryptorates.ai/files/standard.csv?4", ",", "en_US"), 1, true)
```

That being said, the order will still move around since coins come in and drop out of the top 4000.

**Comment by Allerius8** [comment]
Ah, yeah I had suspicion there is some easy way to solve that I dont know of. Thanks, VLOOKUP is working great, just as your sheet.
